title: Celina Turner # your name (or website title) here
logo: "/images/PFP.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <p>Hello there, I'm Celina! I am a Programmer and Data Scientist.<p>
  <br><br>
 Data Listener, Insight Whisperer. 
  <br><br>
  <a href="https://www.linkedin.com/in/celina-turner/" target="_blank">LinkedIn</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
